### ISSUE TITLE
Provide stepping information for Intel CPU

### ISSUE THREAD

**Issue by anatol** [klauspost/cpuid#111]
Here is a cpuinfo data

```
processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
stepping	: 10
microcode	: 0xf0
cpu MHz		: 1259.110
cache size	: 12288 KB
physical id	: 0
siblings	: 12
core id		: 5
cpu cores	: 6
apicid		: 11
initial apicid	: 11
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
```

It looks like `cpuid` does not provide a way to get the "stepping" information. Would it be possible to add API access to such CPU information?

**Comment by klauspost** [comment]
Added in #112 - looked into microcode version, but it appears to be privileged and not available through CPUID.
