### ISSUE TITLE
Request: Virtualbox

### ISSUE THREAD

**Issue by bitnom** [klauspost/cpuid#13]
Assuming it's trivial, can you please add virtualbox support?

Thanks.

**Comment by SvenDowideit** [comment]
@TomAshley303 do you mean "detect that we're in a hypervisor, and tell me which one?"

cos I'm adding `cpuid.CPU.HypervisorName` afm for something I need.

**Comment by SvenDowideit** [comment]
ah, darn, #14 adds some support, but VirtualBox and qemu need DMI support, not just cpuid - so it might not make sense to add the complexity here.
