### ISSUE TITLE
No 'CONTRIBUTING.md' was found

### ISSUE THREAD

**Issue by lubinsz** [klauspost/cpuid#17]
Hi all,
@klauspost 
@abourget 
@ebfe 

I'm from ARM. Currently I want to enable this project on arm64 platform.
Before the contribution, our legal team want to check inbound & outbound license.

I have found the outbound license, but didn't found the inbound license.

In general, the inbound license should be 'Developer Certificate of Origin, version 1.1'.
The legal information of inbound license should be in the file of 'CONTRIBUTING.md'.
And the legal information of outbound license should be in the file 'LICENSE'

Please see the project of 'runc' as reference:
https://github.com/opencontainers/runc/blob/master/CONTRIBUTING.md
https://github.com/opencontainers/runc/blob/master/LICENSE

Thanks.

**Comment by abourget** [comment]
@klauspost I'm fine with adhering to the Dev Cert of Origin.

@lubinsz the previous commits won't be signed off, if we create the CONTRIBUTING.md file with the cert of origin, and what about creating an AUTHORS file, with our names, saying any contributions by these people implicitly sign off their code ?

**Comment by klauspost** [comment]
In general, I would like an indication of the problem we are dealing with, ie. "why is this needed" instead of a straight up solution proposal, that makes it easier to evaluate.

The clean "Developer Certificate of Origin" LGTM, but the linked contribution guidelines seems a bit excessive to this kind of project.

**Comment by klauspost** [comment]
Added PR #18 - would that satisfy the legal team?

**Comment by lubinsz** [comment]
@klauspost 
That's would be fine.
Today, I will launch the legal process.
Please merge the file in PR #18 
Thanks. 👍
