### ISSUE TITLE
Please use semver

### ISSUE THREAD

**Issue by ybbus** [klauspost/cpuid#25]
http://semver.org/
https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by ybbus** [comment]
You really have to argue about semver in go these days? I won't.

**Comment by klauspost** [comment]
You still don't explain what you want - releases are version tagged, if that is what you are asking for.

**Comment by ybbus** [comment]
This is not golang semver: v1.2.3
Since tools like golang module dependencies use this format to so versioning. Any other format ist not recognized as versioned.

**Comment by klauspost** [comment]
Huh? The document you link says:


>The format of the tag must be:
>v<SemVer>

**Comment by ybbus** [comment]
What else should I say... Nevermind....

**Comment by klauspost** [comment]
Instead of being condescending, just write what the problem is - that way you won't look like an arrogant. But communication skills aside, thanks for notifying me, I'll take a look at it tomorrow.

**Comment by ybbus** [comment]
I did write what the problem was if you read the comments 4 and 5 carefully.

But besides this I apologize, caught me on the wrong day... Sorry for that!

**Comment by klauspost** [comment]
No problem. I released v1.2.0 - since there were some small additions.
