### ISSUE TITLE
panic: runtime error: integer divide by zero in physicalCores

### ISSUE THREAD

**Issue by ebfe** [klauspost/cpuid#3]
$ go test
    panic: runtime error: integer divide by zero
    [signal 0x8 code=0x1 addr=0x47cf4a pc=0x47cf4a]
    
    goroutine 1 [running]:
    github.com/klauspost/cpuid.physicalCores(0x0)
            /go/src/github.com/klauspost/cpuid/cpuid.go:595 +0x4a
    github.com/klauspost/cpuid.Detect()
            /go/src/github.com/klauspost/cpuid/cpuid.go:181 +0xc7
    github.com/klauspost/cpuid.init.1()
            /go/src/github.com/klauspost/cpuid/cpuid.go:162 +0x14
    github.com/klauspost/cpuid.init()
            /go/src/github.com/klauspost/cpuid/cpuid_test.go:648 +0x1b0
    main.init()
            github.com/klauspost/cpuid/_test/_testmain.go:176 +0x4a
    exit status 2
    FAIL    github.com/klauspost/cpuid      0.004s

The cpu in question is: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz

threadsPerCore() returns 0. Patching that to always return 1 gives the following info:

        cpuid_test.go:14: Max Function:0xd
        cpuid_test.go:16: Max Extended Function:0x80000008
        cpuid_test.go:19: CPUID.(EAX=07H):EBX: 0x0
        cpuid_test.go:21: Name: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
        cpuid_test.go:22: PhysicalCores: 0
        cpuid_test.go:23: ThreadsPerCore: 1
        cpuid_test.go:24: LogicalCores: 0
        cpuid_test.go:25: Family 6 Model: 23
        cpuid_test.go:26: Features: CMOV,NX,MMX,MMXEXT,SSE,SSE2,SSE3,SSSE3,SSE4.1,CX16
        cpuid_test.go:27: Cacheline bytes: 64
        cpuid_test.go:29: Yay - we have SSE 2

Let me know if you need more information.

**Comment by klauspost** [comment]
Thanks - this should be fixed with 4d555cf08ae34d4370715b35b866627f361781a0

I will see if I can find alternative methods of detecting physical/logical cores.
