### ISSUE TITLE
SGX enabled without any available EPC memory

### ISSUE THREAD

**Issue by klauspost** [klauspost/cpuid#36]
@ipuustin Running tests locally I get this failure:
```
=== RUN   TestSGX
--- FAIL: TestSGX (0.00s)
    cpuid_test.go:284: SGX Support: true
    cpuid_test.go:293: SGX enabled without any available EPC memory
```

**Comment by mythi** [comment]
we can fix this before the release (if you're planning one)

**Comment by klauspost** [comment]
That would be really nice. Probably bc of Windows.

**Comment by ipuustin** [comment]
I'll take a look at this now. It may be that not all SGX-enabled CPUs report the memory, even though I thought they would. Probably we'll need to relax the test condition.
