### ISSUE TITLE
Lack of reverse-vendor-ID mapping makes it difficult to get textual VendorID

### ISSUE THREAD

**Issue by ribasushi** [klauspost/cpuid#42]
The lack of a reverse map for https://github.com/klauspost/cpuid/blob/v1.2.4/cpuid.go#L24-L37 is annoying. The fact that https://github.com/klauspost/cpuid/blob/v1.2.4/cpuid.go#L815-L831 is private makes it essentially impossible to construct such a map without hardcoding names on the implementor side.

Thank you for the otherwise amazing module!

**Comment by klauspost** [comment]
I've exposed the raw vendor string, since that allows you to see the exact vendor and also handle unknown ones.
