### ISSUE TITLE
RFC: How to handle >64 CPU features

### ISSUE THREAD

**Issue by askervin** [klauspost/cpuid#55]
Hi @klauspost,

I'd like to add [AMX](https://fuse.wikichip.org/news/3600/the-x86-advanced-matrix-extension-amx-brings-matrix-operations-to-debut-with-sapphire-rapids/) CPU features AMXBF16, AMXTILE, AMXINT8. However,  we've hit the limit of 64 features in `Flags` (of type `uint64`).

So I'm wondering if you'd have a preference over following options, or a better idea:
- Change `CPUInfo.Features` from `uint64` to an alternative of arbitrary size (like `map[int]bool`, `math.big.Int`, `bitarray`) - and totally break the API.
- Add "next leaf" like `CPUInfo.Features2`.
- Add a "feature leaf" like `CPUInfo.AMX` that would hold subflags for this particular feature.
- Add new feature structure (new API) of arbitrary size with current and new AMX features in it, and keep current `CPUInfo.Features` as is for backwards compatibility.
- Something better?

**Comment by klauspost** [comment]
Yeah, a v2 has been needed for a while. #28 

I think without a full rewrite I would prefer the "feature leaf" option. At least for now what makes it feasible for now. How does that sound?

**Comment by askervin** [comment]
That's perfectly fine. Thanks for quick answer!
Closing.
