### ISSUE TITLE
Inaccurate AVX-512 feature flags on i5-1030NG7

### ISSUE THREAD

**Issue by lukechampine** [klauspost/cpuid#57]
`cpuid` claims that AVX-512F is not supported on my Macbook, but I can execute the instructions just fine. Is this a bug in `cpuid`, or does the i5-1030NG7 report incorrect feature flags?? Here's the full `CPU` struct:
```
{
    BrandName:      "Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz",
    VendorID:       1,
    VendorString:   "GenuineIntel",
    Features:       "CMOV,NX,MMX,MMXEXT,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AVX,AVX2,FMA3,F16C,BMI1,BMI2,LZCNT,POPCNT,AESNI,CLMUL,HTT,RDRAND,RDSEED,ADX,SHA,ERMS,RDTSCP,CX16,SGX,SGXLC,IBPB,STIBP,VMX",
    Arm:            0x0,
    PhysicalCores:  4,
    ThreadsPerCore: 2,
    LogicalCores:   8,
    Family:         6,
    Model:          126,
    CacheLine:      64,
    Hz:             1113600000,
    Cache: {
        L1I: 32768,
        L1D: 49152,
        L2:  524288,
        L3:  6291456,
    },
    SGX: {
        Available:           true,
        LaunchControl:       true,
        SGX1Supported:       false,
        SGX2Supported:       false,
        MaxEnclaveSizeNot64: 1,
        MaxEnclaveSize64:    1,
        EPCSections:         []cpuid.SGXEPCSection{},
    },
    maxFunc:   0x1b,
    maxExFunc: 0x80000008,
}
```

**Comment by klauspost** [comment]
@lukechampine I don't have any AVX512 capable hardware. Do note that OS support is also required for AVX512 to be enabled and VMs may filter out certain CPU features.

Could you check this piece of code with Printf's and see where the detection is stopping?

https://github.com/klauspost/cpuid/blob/fc8eb62d0b3172de22845604984aa48abe034d4e/cpuid.go#L1276

Running `go test -test.v -test.run ^TestCPUID$` should be enough for the code to be triggered.

**Comment by klauspost** [comment]
Running #58 shows AVX-512F detected on Travis' CI setup: https://travis-ci.org/github/klauspost/cpuid/jobs/714792691 so at least in some cases it is detected.

**Comment by lukechampine** [comment]
Looks like `xgetbv(0)` returns 7, so the `OPMASK` state is erroneously reported as 0. I also tried cpu_features with the same result, so this doesn't appear to be a bug in `cpuid`. Sadly, my googling did not turn up anything about why `OPMASK` is incorrect on this CPU.

I *am* able to detect AVX512 support via `sysctl`:
```
$ sysctl -n hw.optional.avx512f
1
```
So I guess I can use `syscall.Sysctl` as a fallback.

**Comment by klauspost** [comment]
@lukechampine This values is supposed to be set by the OS to report that it can handle context swapping ZMM registers and such.

Are you running the latest OS? Seems like an odd thing to forget.

**Comment by lukechampine** [comment]
yep, Catalina 10.15.6 (19G73). Strange indeed.
