### ISSUE TITLE
mac error 

### ISSUE THREAD

**Issue by lichao0111** [klauspost/cpuid#70]
# github.com/klauspost/cpuid
../github.com/klauspost/cpuid/cpuid.go:441:31: invalid operation: 1 << (feat & flagMask) (shift count type FeatureID, must be unsigned integer)
../github.com/klauspost/cpuid/cpuid.go:445:29: invalid operation: 1 << (feat & flagMask) (shift count type FeatureID, must be unsigned integer)
../github.com/klauspost/cpuid/cpuid.go:452:33: invalid operation: 1 << (offset & flagMask) (shift count type FeatureID, must be unsigned integer)
../github.com/klauspost/cpuid/cpuid.go:458:17: invalid operation: 1 << (offset & flagMask) (shift count type FeatureID, must be unsigned integer)

**Comment by klauspost** [comment]
@lichao0111 This is supported from Go 1.13 which is required. Upgrade your Go install.
