### ISSUE TITLE
Incorrect detection of ThreadsPerCore

### ISSUE THREAD

**Issue by max2k1** [klauspost/cpuid#8]
Library incorrectly detects ThreadsPerCore count, so PhysicalCore value is also wrong:

Name: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
PhysicalCores: 1
ThreadsPerCore: 16
LogicalCores: 16
Family 6 Model: 45

**Comment by klauspost** [comment]
Could you run `go test -v -test.run=DumpCPUID` and paste the output here?

**Comment by max2k1** [comment]
$ go test -v -test.run=DumpCPUID=== RUN   TestDumpCPUID--- PASS: TestDumpCPUID (0.00s)    cpuid_test.go:38: CPUID 00000000: 0000000d-756e6547-6c65746e-49656e69    cpuid_test.go:38: CPUID 00000001: 000206d7-03200800-1fbee3ff-bfebfbff    cpuid_test.go:38: CPUID 00000002: 76035a01-00f0b2ff-00000000-00ca0000    cpuid_test.go:38: CPUID 00000003: 00000000-00000000-00000000-00000000    cpuid_test.go:38: CPUID 00000004: 3c004121-01c0003f-0000003f-00000000    cpuid_test.go:45: CPUID 00000004: 3c004122-01c0003f-0000003f-00000000    cpuid_test.go:45: CPUID 00000004: 3c004143-01c0003f-000001ff-00000000    cpuid_test.go:45: CPUID 00000004: 3c07c163-04c0003f-00003fff-00000006    cpuid_test.go:38: CPUID 00000005: 00000040-00000040-00000003-00021120    cpuid_test.go:38: CPUID 00000006: 00000075-00000002-00000009-00000000    cpuid_test.go:38: CPUID 00000007: 00000000-00000000-00000000-00000000    cpuid_test.go:38: CPUID 00000008: 00000000-00000000-00000000-00000000    cpuid_test.go:38: CPUID 00000009: 00000001-00000000-00000000-00000000    cpuid_test.go:38: CPUID 0000000a: 07300403-00000000-00000000-00000603    cpuid_test.go:38: CPUID 0000000b: 00000000-00000000-00000003-00000003    cpuid_test.go:45: CPUID 0000000b: 00000005-00000010-00000201-00000003    cpuid_test.go:38: CPUID 0000000c: 00000000-00000000-00000000-00000000    cpuid_test.go:38: CPUID 0000000d: 00000007-00000340-00000340-00000000    cpuid_test.go:45: CPUID 0000000d: 00000001-00000000-00000000-00000000    cpuid_test.go:45: CPUID 0000000d: 00000100-00000240-00000000-00000000    cpuid_test.go:53: CPUID 80000000: 80000008-00000000-00000000-00000000    cpuid_test.go:53: CPUID 80000001: 00000000-00000000-00000001-2c100800    cpuid_test.go:53: CPUID 80000002: 20202020-49202020-6c65746e-20295228    cpuid_test.go:53: CPUID 80000003: 6e6f6558-20295228-20555043-322d3545    cpuid_test.go:53: CPUID 80000004: 20303636-20402030-30322e32-007a4847    cpuid_test.go:53: CPUID 80000005: 00000000-00000000-00000000-00000000    cpuid_test.go:53: CPUID 80000006: 00000000-00000000-01006040-00000000    cpuid_test.go:53: CPUID 80000007: 00000000-00000000-00000000-00000100    cpuid_test.go:53: CPUID 80000008: 0000302e-00000000-00000000-00000000PASSok      _/home/max2k1/test/src/github.com/klauspost/cpuid    0.004s13.12.2015, 14:23, "Klaus Post" <notifications@github.com>:Could you run go test -v -test.run=DumpCPUID and paste the output here?

**Comment by klauspost** [comment]
Thanks. There is something fishy. I get this output (which I assume is correct):
```
        cpuid_test.go:684: Name: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
        cpuid_test.go:686: Max Function:0xd
        cpuid_test.go:688: Max Extended Function:0x80000008
        cpuid_test.go:689: PhysicalCores: 16
        cpuid_test.go:690: ThreadsPerCore: 1
        cpuid_test.go:691: LogicalCores: 16
        cpuid_test.go:692: Family 6 Model: 45
        cpuid_test.go:693: Features: CMOV,NX,MMX,MMXEXT,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,POPCNT,AESNI,CLMUL,RDTSCP,CX16
        cpuid_test.go:694: Cacheline bytes: 64
        cpuid_test.go:695: L1 Instruction Cache: 32768 bytes
        cpuid_test.go:696: L1 Data Cache: 32768 bytes
        cpuid_test.go:697: L2 Cache: 262144 bytes
        cpuid_test.go:698: L3 Cache: 20971520 bytes
```

Could you also send `go test -v -test.run=TestCPUID`?

**Comment by max2k1** [comment]
:) Results are.. unstable
$ go test -v -test.run=TestCPUID
=== RUN   TestCPUID
--- PASS: TestCPUID (0.00s)
  cpuid_test.go:14: Max Function:0xd
  cpuid_test.go:16: Max Extended Function:0x80000008
  cpuid_test.go:17: Name: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
  cpuid_test.go:18: PhysicalCores: 8
  cpuid_test.go:19: ThreadsPerCore: 2
  cpuid_test.go:20: LogicalCores: 16
  cpuid_test.go:21: Family 6 Model: 45
  cpuid_test.go:22: Features: CMOV,NX,MMX,MMXEXT,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AVX,POPCNT,AESNI,CLMUL,HTT,RDTSCP,CX16
  cpuid_test.go:23: Cacheline bytes: 64
  cpuid_test.go:24: L1 Instruction Cache: 32768 bytes
  cpuid_test.go:25: L1 Data Cache: 32768 bytes
  cpuid_test.go:26: L2 Cache: 262144 bytes
  cpuid_test.go:27: L3 Cache: 20971520 bytes
  cpuid_test.go:30: Yay - we have SSE 2
PASS
ok    _/home/max2k1/test/src/github.com/klauspost/cpuid  0.003s

$ go test -v -test.run=TestCPUID
=== RUN   TestCPUID
--- PASS: TestCPUID (0.00s)
  cpuid_test.go:14: Max Function:0xd
  cpuid_test.go:16: Max Extended Function:0x80000008
  cpuid_test.go:17: Name: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
  cpuid_test.go:18: PhysicalCores: 1
  cpuid_test.go:19: ThreadsPerCore: 16
  cpuid_test.go:20: LogicalCores: 16
  cpuid_test.go:21: Family 6 Model: 45
  cpuid_test.go:22: Features: CMOV,NX,MMX,MMXEXT,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AVX,POPCNT,AESNI,CLMUL,HTT,RDTSCP,CX16
  cpuid_test.go:23: Cacheline bytes: 64
  cpuid_test.go:24: L1 Instruction Cache: 32768 bytes
  cpuid_test.go:25: L1 Data Cache: 32768 bytes
  cpuid_test.go:26: L2 Cache: 262144 bytes
  cpuid_test.go:27: L3 Cache: 20971520 bytes
  cpuid_test.go:30: Yay - we have SSE 2
PASS

**Comment by max2k1** [comment]
This CPU has 8 physical cores + HT enabled. MB is equipped with 2 CPUs.

**Comment by klauspost** [comment]
Thanks for the useful info!

**Comment by klauspost** [comment]
I have merged a change that might fix it. What is the output of `go test -v -test.run=CPUID`?

**Comment by max2k1** [comment]
Now it seems to be ok :) Thanks!
=== RUN   TestCPUID
--- PASS: TestCPUID (0.00s)
	cpuid_test.go:14: Max Function:0xd
	cpuid_test.go:16: Max Extended Function:0x80000008
	cpuid_test.go:17: Name: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
	cpuid_test.go:18: PhysicalCores: 8
	cpuid_test.go:19: ThreadsPerCore: 2
	cpuid_test.go:20: LogicalCores: 16
	cpuid_test.go:21: Family 6 Model: 45
	cpuid_test.go:22: Features: CMOV,NX,MMX,MMXEXT,SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AVX,POPCNT,AESNI,CLMUL,HTT,RDTSCP,CX16
	cpuid_test.go:23: Cacheline bytes: 64
	cpuid_test.go:24: L1 Instruction Cache: 32768 bytes
	cpuid_test.go:25: L1 Data Cache: 32768 bytes
	cpuid_test.go:26: L2 Cache: 262144 bytes
	cpuid_test.go:27: L3 Cache: 20971520 bytes
	cpuid_test.go:30: We have SSE2
PASS

**Comment by klauspost** [comment]
Glad to hear that! Thanks for the report & help!

**Comment by max2k1** [comment]
Now you broke i386 compatibility :(

C:\Golang\src\github.com\klauspost\cpuid>go build
# github.com/klauspost/cpuid
asm: asmins: illegal 64: 00000 (c:\Golang\src\github.com\klauspost\cpuid\cpuid_386.s:5) XORQ    CX, CX

C:\Golang\src\github.com\klauspost\cpuid>go version
go version go1.5.2 windows/386

**Comment by klauspost** [comment]
Ah - wrong register length. I fixed it now. Thanks!

**Comment by max2k1** [comment]
And don't forget about private build :)
