### ISSUE TITLE
I have one my Windows 10 Pro Physical Desktop Machine, still it's returning true for the call cpuid.CPU.VM()

### ISSUE THREAD

**Issue by bhavar12** [klauspost/cpuid#81]
For desktop, I have  Windows 10 Pro as OS on my machine . but  **cpuid.CPU.VM()** this call returning true for my Desktop machine. as it is desktop machine it should return true. attached sample screen shot for reference.

![image](https://user-images.githubusercontent.com/49863798/123934554-06b69580-d9b1-11eb-82c9-d5e109d8fdea.png)

Attaching code sample as well.
[main.go.txt](https://github.com/klauspost/cpuid/files/6739557/main.go.txt)
 anyone help me on this.

**Comment by klauspost** [comment]
@bhavar12 Mine is showing the same because Windows is running in HyperV mode used for Docker and WSL.

So you are likely running in a VM without knowing it.

**Comment by bhavar12** [comment]
@klauspost but I have not enable any HyperV roles feature on that machine.

**Comment by klauspost** [comment]
@bhavar12 

In powershell, what is the output of `Get-ComputerInfo -property "HyperVisorPresent"`?

**Comment by bhavar12** [comment]
above command giving true as output.

**Comment by klauspost** [comment]
@bhavar12 You are technically running Windows in a VM.
