### ISSUE TITLE
CPU without L3 cache shows -1 bytes of L3

### ISSUE THREAD

**Issue by YetAnotherRussian** [klauspost/cpuid#85]
Reference CPU:

![image](https://user-images.githubusercontent.com/4670472/130235778-13334516-89b8-437b-8c21-4232ecb4ecbc.png)

Test CPU - Intel Pentium J5005:

![image](https://user-images.githubusercontent.com/4670472/130237239-478aff5f-64a3-4619-aad4-fa8cd40010cd.png)

Should be zero, should it? Third-parties go mad because ot this (such as github.com/dustin/go-humanize if we try to prettify the output)

**Comment by klauspost** [comment]
The documentation states:

`L3  int // L3 Cache (per core, per ccx or shared). Will be -1 if undetected`

When a cache level isn't specified, it doesn't technically mean that it doesn't exist.

I just tried setting it to 0 when *some* cache information is present, but some are still wrong, eg:

```
    mockcpu_test.go:175: Opening GenuineIntel00006FB_Conroe_CPUID.txt
    mockcpu_test.go:178: Name: Intel(R) Core(TM)2 Duo CPU     E6750  @ 2.66GHz
    mockcpu_test.go:180: Max Function:0xa
    mockcpu_test.go:182: Max Extended Function:0x80000008
    mockcpu_test.go:183: VendorString: GenuineIntel
    mockcpu_test.go:184: VendorID: Intel
    mockcpu_test.go:185: PhysicalCores: 2
    mockcpu_test.go:186: ThreadsPerCore: 1
    mockcpu_test.go:187: LogicalCores: 2
    mockcpu_test.go:188: Family 6 Model: 15
    mockcpu_test.go:189: Features: CMOV,CX16,MMX,MMXEXT,NX,SSE,SSE2,SSE3,SSSE3,VMX
    mockcpu_test.go:190: Cacheline bytes: 64
    mockcpu_test.go:191: L1 Instruction Cache: 0 bytes
    mockcpu_test.go:192: L1 Data Cache: 32768 bytes
    mockcpu_test.go:193: L2 Cache: 0 bytes
    mockcpu_test.go:194: L3 Cache: 0 bytes
    mockcpu_test.go:195: Hz: 2660000000 Hz
    mockcpu_test.go:196: Boost: 0 Hz
```
This CPU has [4MB L2 cache AFAICT](https://www.cnet.com/products/intel-core-2-duo-e6750-2-66ghz/), but it is not reported.

So `-1` is "unknown". You have to handle that.
