### ISSUE TITLE
main.go:7:2: cannot find package "github.com/klauspost/cpuid/v2" in any of:

### ISSUE THREAD

**Issue by fyhong** [klauspost/cpuid#87]
I listened to your suggestion.
now use github.com/klauspost/cpuid as import path, but it shows

github.com/go-sql-driver/mysql
../../go-sql-driver/mysql/driver.go:88:33: undefined: driver.Connector
../../go-sql-driver/mysql/driver.go:99:49: undefined: driver.Connector
../../go-sql-driver/mysql/nulltime.go:36:15: undefined: sql.NullTime

github.com/klauspost/cpuid
../../klauspost/cpuid/cpuid.go:394:30: syntax error: unexpected _000_000 at end of statement
../../klauspost/cpuid/cpuid.go:398:37: syntax error: unexpected _000_000 at end of statement

**Comment by klauspost** [comment]
@fyhong Upgrade your Go.

**Comment by fyhong** [comment]
golang is the newest version

**Comment by klauspost** [comment]
@fyhong No, it is not. Check `go version`.
