### ISSUE TITLE
Support for memory encryption cpuids (AMD SME, SEV and Intel TME)

### ISSUE THREAD

**Issue by iFrozenPhoenix** [klauspost/cpuid#99]
It would be good to have support for AMD SME and SEV and Intel TME cpuids.

**Comment by klauspost** [comment]
AMD: https://github.com/klauspost/cpuid/pull/100

Note, that this detects if the feature is *available*, not if it is enabled. This would require kernel level privileges.

**Comment by klauspost** [comment]
Intel: #102

**Comment by iFrozenPhoenix** [comment]
@klauspost thank you very much for the rapid implementation.
I've already tested it and can confirm that it works.
